FROM alpine:3.15

ENV LANG=C.UTF-8

RUN apk update && \
    apk upgrade && \
    apk add --no-cache openjdk17-jdk

ARG APP_NAME
ARG APP_VERSION

ENV APP_NAME=$APP_NAME
ENV APP_VERSION=$APP_VERSION

# Crea un grupo y un usuario no root
RUN addgroup -S appgroup && adduser -S -G appgroup appuser

WORKDIR /opt/

# Cambia la propiedad del directorio de trabajo al usuario no root
RUN chown -R appuser:appgroup /opt/

# Agrega el archivo JAR de la aplicación al contenedor
ADD "target/${APP_NAME}-${APP_VERSION}.jar" .

# Cambia la propiedad del archivo JAR al usuario no root
RUN chown appuser:appgroup "${APP_NAME}-${APP_VERSION}.jar"

# Expone el puerto ::
EXPOSE 8086

# Cambia al usuario no root
USER appuser

# Comando de entrada para ejecutar la aplicación
ENTRYPOINT java -Duser.timezone=America/Lima \
                           -jar "${APP_NAME}-${APP_VERSION}.jar"